export const Products = [
  {
    id: 1,
    name: "Paracetamol 500mg - 20 tabletas",
    description: "Marca: Genven",
    size: ["Caja con 20 tabletas"],
    price: 3.5,
    disable: false,
  },
  {
    id: 2,
    name: "Ibuprofeno 400mg - 30 tabletas",
    description: "Marca: Drotafarma",
    size: ["Caja con 30 tabletas"],
    price: 5.0,
    disable: false,
  },
  {
    id: 3,
    name: "Amoxicilina 500mg - 21 cápsulas",
    description: "Marca: Zuzu",
    size: ["Caja con 21 cápsulas"],
    price: 8.5,
    disable: false,
  },
  {
    id: 4,
    name: "Loratadina 10mg - 10 tabletas",
    description: "Marca: Genven",
    size: ["Caja con 10 tabletas"],
    price: 4.0,
    disable: false,
  },
  {
    id: 5,
    name: "Omeprazol 20mg - 14 cápsulas",
    description: "Marca: Drotafarma",
    size: ["Caja con 14 cápsulas"],
    price: 6.0,
    disable: false,
  },
  {
    id: 6,
    name: "Salbutamol Inhalador - 200 dosis",
    description: "Marca: Zuzu",
    size: ["Inhalador de 200 dosis"],
    price: 12.0,
    disable: false,
  },
  {
    id: 7,
    name: "Metformina 850mg - 30 tabletas",
    description: "Marca: Genven",
    size: ["Caja con 30 tabletas"],
    price: 7.5,
    disable: false,
  },
  {
    id: 8,
    name: "Losartán 50mg - 28 tabletas",
    description: "Marca: Drotafarma",
    size: ["Caja con 28 tabletas"],
    price: 9.0,
    disable: false,
  },
];
